
services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: aiops-gitlab
    hostname: gitlab
    restart: always
    ports:
      - "8081:80"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  jenkins:
    build: ./jenkins
    container_name: aiops-jenkins
    hostname: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:community
    container_name: aiops-sonarqube
    hostname: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  ai-agent:
    build: ../ai-governance-agent
    container_name: aiops-agent
    hostname: aiops
    restart: always
    ports:
      - "8000:8000"
    volumes:
    - ../ai-governance-agent/ai-data:/app/storage

  postgres:
    image: postgres:16
    container_name: aiops-postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: aiops
      POSTGRES_PASSWORD: aiops
      POSTGRES_DB: aiops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: aiops-grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

volumes:

  jenkins_home:
  sonarqube_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgres_data:
  grafana_data: